server:
  port: 8000
spring:
  application:
    name: user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wf
    url: jdbc:mysql://localhost:3306/wf-init
  redis:
    host: 192.168.43.129
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 3000

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Redis
